fast_lio:
    feature_extract_enable: false          # <param name="feature_extract_enable" ...>
    point_filter_num: 3                   # <param name="point_filter_num" ...>
    max_iteration: 3                      # <param name="max_iteration" ...>
    filter_size_corner: 0.1               # not in launch, but C++ asks for it
    filter_size_surf: 0.1                 # <param name="filter_size_surf" ...>
    filter_size_map: 0.1                  # <param name="filter_size_map" ...>
    cube_side_length: 1000                # <param name="cube_side_length" ...>
    runtime_pos_log_enable: true          # <param name="runtime_pos_log_enable" ...>
    scan_rate: 10
    common:
        lid_topic:  "base_front_mid_lidar_points"
        imu_topic:  "front_mid_lidar_imu_transformed" # /mavros/imu/data /ouster/imu /imu/data
        time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
        time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                    # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
    preprocess:
        lidar_type: 5                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
        scan_line: 96
        timestamp_unit: 0                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
        blind: 0
    mode:
        init_from_odom: true
        fast_odom_frame: "r5000219a8/odom"
        fast_base_frame: "r5000219a8/fast_lio_pose"
    mapping:
        max_search_dist_surf: 1.0 # default: 5
        num_sub_cloud: 1
        acc_cov: 0.1
        gyr_cov: 0.1
        b_acc_cov: 0.0001
        b_gyr_cov: 0.0001
        fov_degree:    120
        det_range:     200.0
        extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
        extrinsic_T: [ 0.0, 0.0, 0.0 ]
        extrinsic_R: [0, 0, 1,
                    0, 1, 0,
                    -1, 0, 0]
    publish:
        path_en:  true
        scan_publish_en:  true       # false: close all the point cloud output
        dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
        scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
    pcd_save:
        pcd_save_en: false
        interval: -1                 # how many LiDAR frames saved in each pcd file;
                                    # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
